[LightDM]

# Enable guest-account via the required script; it must be on /usr/sbin
# or /usr/bin (usually the latter since the "/usr merge")
guest-account-script=guest-account

[Seat:*]

# disable guest sessions (a guest session requires a valid default
# user-session parameter, see below)
allow-guest=true
greeter-allow-guest=true
